module.exports = {
  1: {realName: 'Quinn Pelichoff', fakeName: 'Brad McKenzie'},
  2: {realName: 'Jason Sun', fakeName: 'Devan Green'},
  3: {realName: 'Etienne Karleskind', fakeName: 'Jonathon Bartell'},
  4: {realName: 'Jovani Ghorbani', fakeName: 'Aditya Heathcote'},
  5: {realName: 'Marcus Roizen', fakeName: 'Keegan Boyle'},
  6: {realName: 'Jack Vankoll', fakeName: 'Filiberto Labadie'},
  7: {realName: 'Tibor Thomason', fakeName: 'Adonis Rempel'},
  8: {realName: 'Liam Heuser', fakeName: 'Carolyn Fritsch'},
  9: {realName: 'Andrew Cho', fakeName: 'Theresia Swaniawski'},
  10: {realName: 'Andrew Moore', fakeName: 'Alfonso Spinka'},
  11: {realName: 'Nick Van Ardenne', fakeName: 'Savannah Kris'},
  12: {realName: 'Nick Rachwald', fakeName: 'Rosamond Howell'},
  13: {realName: 'Gavin McLaren', fakeName: 'Jarrett Weber'},
  14: {realName: 'Julian Fairbanks', fakeName: 'Irwin Murray'},
  15: {realName: 'Kevork Tchakmakjian', fakeName: 'Cierra Wyman'},
  16: {realName: 'Angelo Badillo', fakeName: 'Jarret Sawayn'},
  17: {realName: 'Ryan Vaughn', fakeName: 'Laisha Zboncak'},
  18: {realName: 'Ethan Hiew', fakeName: 'Javonte Fay'},
  19: {realName: 'Kai Hoite', fakeName: 'Kraig Smith'},
  20: {realName: 'William Payne', fakeName: "Candelario O'Connell"},
  21: {realName: 'Kobe Martin', fakeName: 'Annabell Haag'},
  22: {realName: 'Patrick Kenneally', fakeName: 'Meredith Price'},
  23: {realName: 'Peter Murphy', fakeName: 'Esther Berge'},
  24: {realName: 'Suhaib Mumtaz', fakeName: 'Bessie Witting'},
  25: {realName: 'Gordon Dailey', fakeName: 'Axel Lind'},
  26: {realName: 'Cooper Alford', fakeName: 'Chance Thompson'},
  28: {realName: 'Carter Young', fakeName: 'Gretchen Schmeler'},
  29: {realName: 'Casey Studebaker', fakeName: 'Lina Larkin'},
  30: {realName: 'Jonathan Pham', fakeName: 'Hillary Cummerata'},
  31: {realName: 'Aram Jelalian', fakeName: 'Casimer Hahn'},
  32: {realName: 'Spencer Dettlinger', fakeName: 'Ardella Denesik'},
  33: {realName: 'Caleb Kim', fakeName: 'Jamil Roberts'},
  34: {realName: 'Sam DeLuca', fakeName: 'Xander Goldner'},
  35: {realName: 'Jack Keough', fakeName: 'Duane Mayert'},
  36: {realName: 'Chris Noga', fakeName: 'Mellie Brown'},
  37: {realName: 'Hayden Page', fakeName: 'Felipa Treutel'},
  38: {realName: 'Christoph Karleskind', fakeName: 'Justina Feil'},
  39: {realName: 'Edouard Karleskind', fakeName: 'Rose Huels'},
  40: {realName: 'Cam Kumagai', fakeName: 'Fae Kiehn'},
  41: {realName: 'Ariel de la Campa Everette', fakeName: 'Carmela Hudson'},
  42: {realName: 'Zen Yoshida', fakeName: 'Maurine DuBuque'},
  43: {realName: 'Daniel Jarotzky', fakeName: 'Duane Daniel'},
  44: {realName: 'Sam Goldberg', fakeName: 'Breanna Veum'},
  45: {realName: 'Adrien Alvira', fakeName: 'Tara Berge'},
  46: {realName: 'Jack Woll', fakeName: 'Carlos Luettgen'},
  47: {realName: 'Richard Reid', fakeName: "Jaqueline O'Conner"},
  48: {realName: 'Jake Gunderman', fakeName: 'Abby Kub'},
  49: {realName: 'Max Kreutzelman', fakeName: 'Tomas Will'},
  50: {realName: 'Wilson Baatar', fakeName: 'Kenneth Brekke'},
  51: {realName: 'Anthony Banis', fakeName: 'Bradly Romaguera'},
  52: {realName: 'Tibor Thompson', fakeName: 'Brennan Jast'},
  53: {realName: 'Andrew Simpson', fakeName: 'Jacquelyn Rice'},
  54: {realName: 'Adrian Layer', fakeName: 'Jena Runolfsson'},
  55: {realName: 'Stewart Fetzko', fakeName: 'Savanah Kunde'},
  56: {realName: 'Luca Frippiat', fakeName: 'Joan Hilpert'},
  57: {realName: 'John Mark Ozaeta', fakeName: 'Adelle Orn'},
  58: {realName: 'Cameron Thomas', fakeName: 'Ramiro Schmeler'},
  59: {realName: 'Matthew Boranian', fakeName: 'Consuelo Ruecker'},
  60: {realName: 'Jack Berger', fakeName: 'Percival Morissette'},
  61: {realName: 'Lucas Feddersen', fakeName: 'Joe Tremblay'},
  62: {realName: 'Mills Haskett', fakeName: 'Emilia Von'},
  63: {realName: 'Marius van Dongen', fakeName: 'Breanna Gerhold'},
  64: {realName: 'Griffin Geary', fakeName: 'Marisa Weissnat'},
  65: {realName: 'Matt Schade', fakeName: 'Carolyn Lebsack'},
  66: {realName: 'Gunnar Holm', fakeName: 'Hadley Kihn'},
  67: {realName: 'Jacob Corfey', fakeName: 'Hilda Moore'},
  68: {realName: 'Will Hosler', fakeName: 'Lacy Hegmann'},
  69: {realName: 'Cyrus Lim', fakeName: 'Webster Lesch'},
  70: {realName: 'Aidan Schooley', fakeName: 'Lewis Gibson'},
  71: {realName: 'Michael Massullo', fakeName: 'Oscar Powlowski'},
  72: {realName: 'Karl Lesterhuis', fakeName: 'Milan Kshlerin'},
  73: {realName: 'Luke Connolly', fakeName: 'Doug Hauck'},
  74: {realName: 'Grant Park', fakeName: 'Terry Bergnaum'},
  75: {realName: 'Michael Massulo', fakeName: 'Jensen Crist'},
  76: {realName: 'Max Jaenike', fakeName: 'Osvaldo Schuppe'},
  77: {realName: 'Cole Lukas', fakeName: 'Nakia Kub'},
  78: {realName: 'Max Karleskind', fakeName: 'Henri Sporer'},
  79: {realName: 'Ethan Yen', fakeName: 'Pearl Kuphal'},
  80: {realName: 'Andrew Stoddard', fakeName: 'Logan Renner'},
  81: {realName: 'Christian Granados', fakeName: 'Anya Grimes'},
  82: {realName: 'Lorenzo Nazzari', fakeName: 'Pedro Davis'},
  83: {realName: 'Ollie Elmgren', fakeName: "Misty O'Conner"},
  84: {realName: 'Jack Saroni', fakeName: 'Juliet Kulas'},
  85: {realName: 'Jake Benham', fakeName: 'Sincere Hansen'},
  86: {realName: 'Santiago Robles', fakeName: 'Reynold Bayer'},
  87: {realName: 'Christian Espos', fakeName: 'Bessie Torphy'},
  88: {realName: 'Noah Kim', fakeName: 'Jonathon Ziemann'},
  89: {realName: 'Ryan Tripp', fakeName: 'Tony Rippin'},
  90: {realName: 'Sina Panah', fakeName: 'Marisol Champlin'},
  91: {realName: 'Owen Reilly', fakeName: 'Zoey Sawayn'}
}

// for (let key in names) {
//   console.log(`${key}|${names[key].realName}|${names[key].fakeName}`)
// }